#!/bin/csh
#
# Adapted by Joao Lins, Instituto de Quimica da U.F.R.J.
#
# For really large computations, you can ultimately try:
# 1,\$s/numprm=400/numprm=1600/
#
# To increase maximum allowed connections (In xwin.c change #define MXCON 8)
# 1,\$s/mxcon=8/mxcon=10/
#
# To increase maximum number of atoms for the Z-matrix (For converting
# proteins to Z-matrix) (Also change in xwin.c: #define MAXAT 1000)
# 1,\$s/maxat=1000/maxat=20000/
#
# 1,\$s/maxorb=256/maxorb=1024/
#
# For more grid points try (For Gaussian and Vasp cube files)
# 1,\$s/max3d=61/max3d=122/
#
# IMPORTANT: molden3.7 has dynamic memory alloaction for the maxorb stuff
#            and for the protein Z-Matrix (the latter not for z-mat reading)
#            So the maxorb, maxat and max3d parameters should in general not be
#            tampered with
#
cat <<EOF > /tmp/sed.tmp
1,\$s/numatm=300/numatm=500/
EOF
#
foreach file ( *.f )
   echo Operating on $file
   mv $file ${file}.org
   sed -f /tmp/sed.tmp ${file}.org > $file
end
rm -f /tmp/sed.tmp
