# -*- coding: utf-8 -*-
"""
Created on Fri Dec 18 14:53:09 2020

@author: lioneltruflandier
"""

#import os.path
import re, sys
sys.path.append('../../')

from pylab import plot, show, legend
import matplotlib.pylab as plt
from numpy import size, exp, array, zeros
from scipy.optimize import curve_fit

from src.gto_fit_r         import gauss3, gto_fit_orb
#from src.gto_fit           import gauss3, gto_fit_orb
from src.read_write_files_r import read_ion, orbital
from src.read_write_files_r import write_gto, read_gto
from src.plot_orbitals      import color_list_orbital, color_list_orbital_fit
from src.plot_orbitals      import plot_GTO_PAO, plot_GTO_PAO_dev, plot_GTO_prim, plot_PAO
from src.read_write_files_r   import build_guess


#%% Edit file names ###########################################################

# file generated by  MakeIonFiles to extract obitals data 
filename_ion='NaCQ.ion'         
# file to write the GTO fit results formatted for Conquest
filename_gto_write='NaCQ.gto_DZP_3G' 
# file to read in order to build an initial guess (not mandatory)
#filename_gto_read ='NaCQ.gto_DZP_3G_guess' 

#%% Read the ion file genrerated by MakeIonFiles
# return the chemical symbol, the number orbitals @(norb) 
# and the orbitals as the class orb 
# (cf. read_ion.py file in ../../src)  
symbol, norb, orb, kind = read_ion( filename_ion )

#%% Plot PAO only #############################################################
#plot_PAO( orb, filename_gto_write )

#%% Define the initial guess for each orb. ####################################
# (not mandatory)
#
#center = False
#orb_guess = read_gto(filename_gto_read)
#build_guess( orb, orb_guess, center =center)
#
#for i in range(norb):
#   orb[i].guess = orb_guess[i].guess  
#
#orb[3].guess = array([0.2, 0.8, 2.0, 0.6, 0.4, 0.1, 0.4, 0.3])
#orb[3].guess = array([1.129206,-6.765480,0.0094741,0.333977,1.129179,1.338080])
#orb[3].guess = array([0.060565,0.085543,3.339339,-0.727125,1.287382,-0.402082])
#orb[3].guess = array([0.340524815, 3.2450659895, 0.4537962082, 0.1019009042, 0.2253588404, 0.9568838539])
#orb[4].guess = array([0.2562495828,0.0448789897,1.3956907804,-0.5875230482,0.6061962128,-0.2176848311])
#orb[2].guess = array([ 0.1,-1,5,-1,1,1])
#orb[4].guess = array([ 0.1,-1,5,-1,1,1])
#orb[3].guess = array([ 0.060565,0.085543,,-2.750408])
#%% Define the number of Gaussian primitives for each orb. ####################
# (not mandatory, default is 3)
#
#for i in range(norb):
#    orb[i].nG.append(3)
orb[0].nG = 3
orb[2].nG = 3
orb[3].nG = 3
orb[4].nG = 3
#
#%% Fit the radial part and plot ##############################################
for i in range(norb):
    x = array(orb[i].x)
    y = array(orb[i].y)
    # 
    # GTO fit ; plots of the GTO radial part is done in gto_fit_orb
    center = True
    param, nG = gto_fit_orb( x, y, orb[i].nG, orb[i].guess, orb[i].n, orb[i].lname, orb[i].z, i, center = center)

    #
    # If the number of Gaussian has not been setup ; 
    # gto_fit_orb set it to 3 by default
    if ( orb[i].nG == 0 ):
        orb[i].nG = nG
    #
    # Store GTO exponent (a) and coefficient (d)
    
    print(param) 
    if (center == False):
        for j in range(0,orb[i].nG*3,3):
            orb[i].gto_a.append( param[j]   )      
            orb[i].gto_d.append( param[j+1] )
            orb[i].gto_c.append( param[j+2] )
    else:
        for j in range(0,orb[i].nG*2,2):
            orb[i].gto_a.append( param[j]   )      
            orb[i].gto_d.append( param[j+1] )
            orb[i].gto_c.append( 0.0 )
         
    # Generate and store GTO fit results on the radial grid
    orb[i].y_fit_gto()

#%% Write GTO file ############################################################
write_gto( filename_gto_write, symbol, orb, True )
    
#%% Plot radial part of the orbitals ##########################################
plot_GTO_PAO( orb, filename_gto_write )

#%% Plot PAO-GTO deviation ####################################################
plot_GTO_PAO_dev( orb, filename_gto_write )

#%% For each orb plot the GTO primitives ######################################
plot_GTO_prim( orb, filename_gto_write )

