# -*- coding: utf-8 -*-
"""
Created on Fri Dec 18 14:53:09 2020

@author: lioneltruflandier
"""

import os.path
import re, sys
sys.path.append('../')

import matplotlib.pylab as plt
from numpy import size, exp, array, zeros

from reference.src.plot_orbitals_src import read_ion, orbital, plot_PAO

#%% Edit file names ###########################################################

# file generated by  MakeIonFiles to extract obitals data 
filename_ion='Cl.ion'

# file basename to backup the plot (pdf format) 
filename_write='plot_orbitals'

#%% Read the ion file genrerated by MakeIonFiles
# return the chemical symbol, the number orbitals @(norb), the orbitals as the 
# class orb, and the kind of basis set (SZP, DZP etc...)
symbol, norb, orb, kind = read_ion( filename_ion )

#%% Plot radial part of the orbitals ##########################################
plot_PAO( orb=orb, normalize=False, filename=filename_write )
